version: "3.8"

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    container_name: elasticsearch
    # NEW ELASTICSEARCH
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    # OLD ELASTICSEARCH
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  
  # Kibana
  kibana:
    container_name: kibana
    # NEW KIBANA
    image: docker.elastic.co/kibana/kibana:8.9.1
    #OLD KIBANA
    #image: docker.elastic.co/kibana/kibana:7.6.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
      
volumes:
  elasticsearch-data:
    driver: local
